### ISSUE TITLE
[Question] add xml schemas file for Gnome/Budgie and Mate...

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-wallpapers-18.0#1]
... not sure if also Cinnamon use it.. 
@oberon2007 this file is needed for see the widescreen of the wallpapers in Gnome and Mate.. i have create a bash script for do the work automatically during the build of pkgs for my DE (Gnome, Budgie and Mate ) .. can i add the scripts here or in the Extra repo where is present the PKGBUILD ? 
This is what i mean
https://github.com/manjaro/packages-community/blob/master/gnome/gnome-wallpapers/PKGBUILD#L29
https://github.com/Ste74/Gnome-Artwork/blob/master/backgrounds-xml.sh

Of course only if is usefull :stuck_out_tongue_winking_eye:

**Comment by Ste74** [comment]
@oberon2007 can you grant access here? Is ok for you what i want do above?  :wink:

**Comment by oberon2007** [comment]
Works :+1: in principle: 
![image](https://user-images.githubusercontent.com/11800714/40273212-978c756e-5bbc-11e8-8fbf-227faae28e2a.png)

Just, unfortunately now there are now proper names added for the pictures.
Maybe the script should  at least cut the path and only use what is between the last slash and the dot before the extention... :wink: ?
So **/usr/share/backgrounds/Stefanos_favourite.jpg** would be named just **Stefanos_favourite**? :smile: 

current manually created Cinnamon:
![cinnamon](https://user-images.githubusercontent.com/11800714/40273189-1eda5bea-5bbc-11e8-8be2-7bf705e9d197.png)

auto-created 18.0:
![screenshot_2018-05-19_23-17-40](https://user-images.githubusercontent.com/11800714/40273192-2635bfec-5bbc-11e8-9b93-d42042502313.png)

btw. Could we maybe call the folder more meaningful "Illyria" instead of just "18.0" ?

Thank you!

**Comment by Ste74** [comment]
:smile: funny.. Cinnamon do the preview in a different way ... in Gnome i see only the picture and not the name or the path .. anyway let me see what i can do .. what you see when install the gnome background vanilla without any re work about you ?

**Comment by oberon2007** [comment]
I didn't change anything in Gnome's xml file. I only renamed it.
They are displayed like this:

![image](https://user-images.githubusercontent.com/11800714/40276370-b383bb6e-5c08-11e8-9146-7b4261190cec.png)

**Comment by Ste74** [comment]
Ok.. Now i go out but this evening i can modify the script and makefile ;)

**Comment by Ste74** [comment]
@oberon2007 is ok for you the name **Illyria** for the folder ? **/usr/share/backgrounds/Illyria**? ( https://github.com/manjaro/manjaro-wallpapers-18.0/commit/70207a0973d0c29baa5c08958e0265aff98223b6 ) 
And what you mean here: 

> Maybe also we should rename 'Backgrounds' to 'Manjaro' or 'Cinnamon' or so ...

? 
I can rename the folder to collect the Wallpapers for any editions but in any case i like place into the **/usr/share/backgrounds** as main folder I.E. for Gnome example i have put my wallpapers collection into **/usr/share/backgrounds/manjaro-gnome**.. you like only **/usr/share/backgrounds/gnome** ?

**Comment by Ste74** [comment]
Closed 
https://github.com/manjaro/manjaro-wallpapers-18.0/releases/tag/1.3
